### ISSUE TITLE
Using rpms on CentOS 7

### ISSUE THREAD

**Issue by thorgrin** [VUTBR/libnf#10]
I was trying to build some packages against the libnf 1.26 on CentOS 7 and there are some problems:
```
DEBUG util.py:421:  Transaction check error:
DEBUG util.py:421:    file /usr/include/ffilter.h conflicts between attempted installs of libnf-devel-1.26-1.x86_64 and libnf-1.26-1.x86_64
DEBUG util.py:421:    file /usr/lib64/libnf.so.1.0.26 conflicts between attempted installs of libnf-devel-1.26-1.x86_64 and libnf-1.26-1.x86_64
```

It seems that you have the same files in multiple packages in the spec file. Fedora 24 is quite OK with that, but both CentOS 7 is so unhappy that it won't install both packages at once. You should probably keep each installed file in exactly one package.

**Comment by tpoder1** [comment]
Solved in in commit 8dbf03d. Header files will be available only in libnf-devel.
