### ISSUE TITLE
Missing step in README

### ISSUE THREAD

**Issue by cejkato2** [VUTBR/libnf#2]
In `INSTALLATION FROM GIT REPOSITORY` it seems to me that `./configure` is missing before the step 4.

How to repeat the problem:
1) clone (recursive)
2) cd libnf
3) ./prepare-nfdump.sh
4) make fails - missing Makefile

Suggestion: replace `4. Follow instructions 4. and 5. from TARBALL INSTALLATION` with `4. Follow instructions 3., 4. and 5. from TARBALL INSTALLATION`

**Comment by tpoder1** [comment]
Fixed in b25aaed
