### ISSUE TITLE
Question: versioning libnf.so

### ISSUE THREAD

**Issue by cejkato2** [VUTBR/libnf#5]
Is it planned to set version libnf.so?
It would be better for recognition of different library versions installed in the system.

Using libtool's `version-info` e.g. `libnf_la_LDFLAGS= -version-info ...` in `Makefile.am`
Algorithm for choosing the next version number is copied e.g. here https://github.com/CESNET/Nemea-Framework/blob/master/libtrap/README#L20

**Comment by tpoder1** [comment]
Solved in packages > 1.25
