### ISSUE TITLE
make distcheck fails

### ISSUE THREAD

**Issue by jwrona** [VUTBR/libnf#6]
Although I used --recursive option, I'm still receiving following error:

checking for ffilter.h... no
configure: error: !! Required ffilter.h header file not found
        !! If you are using sources from git, please make sure
        !! that you cloned slources with --recursive option
        !! E.g. git clone --recursive https://github.com/VUTBR/libnf
make: **\* [distcheck] Error 1

**Comment by tpoder1** [comment]
Thanks for report. Fixed in  bd6c2b2
